services:
  - type: web
    name: football-frontend
    env: static
    staticPublishPath: /build
    buildCommand: npm install && npm run build
    envVars:
      - key: VITE_API_URL
        value: "https://football-backend.onrender.com"

  - type: web
    name: football-backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
